export const SERVICE_PROVIDER_STRENGTHS = [
  { title: "Hardworking", value: "hardworking" },
  { title: "Reliable", value: "reliable" },
  { title: "Punctual", value: "punctual" },
  { title: "Quick Learner", value: "quick-learner" },
  { title: "Adaptable", value: "adaptable" },
  { title: "Team Player", value: "team-player" },
  { title: "Problem Solver", value: "problem-solver" },
  { title: "Detail-Oriented", value: "detail-oriented" },
  { title: "Creative", value: "creative" },
  { title: "Tech-Savvy", value: "tech-savvy" },
  { title: "Self-Motivated", value: "self-motivated" },
  { title: "Responsible", value: "responsible" },
  { title: "Organized", value: "organized" },
  { title: "Excellent Communicator", value: "excellent-communicator" },
  { title: "Flexible Schedule", value: "flexible-schedule" },
  { title: "Multitasker", value: "multitasker" },
  { title: "Leader", value: "leader" },
  { title: "Customer-Focused", value: "customer-focused" },
  { title: "Positive Attitude", value: "positive-attitude" },
  { title: "Eager to Learn", value: "eager-to-learn" },
  { title: "Initiative Taker", value: "initiative-taker" },
  { title: "Efficient", value: "efficient" },
  { title: "Analytical Thinker", value: "analytical-thinker" },
  { title: "Strong Work Ethic", value: "strong-work-ethic" },
  { title: "Good Listener", value: "good-listener" },
  { title: "Confident", value: "confident" },
  { title: "Empathetic", value: "empathetic" },
  { title: "Resourceful", value: "resourceful" },
  { title: "Patient", value: "patient" },
  { title: "Independent", value: "independent" },
  { title: "Innovative", value: "innovative" },
  { title: "Quality-Oriented", value: "quality-oriented" },
  { title: "Goal-Oriented", value: "goal-oriented" },
  { title: "Collaborative", value: "collaborative" },
  { title: "Professional Demeanor", value: "professional-demeanor" },
  { title: "Time Management Skills", value: "time-management-skills" },
  { title: "Teamwork Skills", value: "teamwork-skills" },
  { title: "Problem-Solving Skills", value: "problem-solving-skills" },
  { title: "Critical Thinker", value: "critical-thinker" },
];
